### ISSUE TITLE
Crashes when launching NSD

### ISSUE THREAD

**Issue by rsabhilash** [openbaton/go-docker-vnfm#3]
I was trying to run an NS on top of docker following this [tutorial-docker](https://openbaton.github.io/documentation/tutorial-docker/). But go-docker-vnfm crashes every time I tries to launch NSD. 

```
panic: interface conversion: interface {} is *catalogue.BaseVimInstance, not *catalogue.DockerVimInstance

goroutine 40 [running]:
github.com/openbaton/go-docker-vnfm/handler.(*HandlerVnfmImpl).Instantiate(0xc420231bc0, 0xc4200abd40, 0x0, 0x0, 0xc420175dd0, 0x0, 0xc42014aae0
, 0x0)
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/handler/handler.go:75 +0xf1a
github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk.(*worker).handleInstantiate(0xc420174b10, 0xc42008c1c0, 0xb
, 0xc42023f980, 0x56efc2)
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk/worker.go:143 +0x998
github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk.handleMessage(0xc257a0, 0xc4201743c0, 0xc420174b10, 0xc4203
00db0, 0x1)
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk/handler.go:61 +0xd43
github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk.handleNfvMessage(0xc420272800, 0x4001, 0x4800, 0x94e580, 0x
c420174b10, 0x0, 0x0, 0xc4200982a0, 0x0, 0x0)
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/vnfmsdk/handler.go:25 +0x465
github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/sdk.(*VnfmManager).Serve.func1(0xc4201b0060, 0x94e580, 0xc420174b10
)
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/sdk/commonsdk.go:337 +0x3dd
created by github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/sdk.(*VnfmManager).Serve
        /home/baton/go/src/github.com/openbaton/go-docker-vnfm/vendor/github.com/openbaton/go-openbaton/sdk/commonsdk.go:318 +0x7e
```

**Comment by gc4rella** [comment]
which version of the NFVO are you using?

**Comment by rsabhilash** [comment]
It's 5.2.0
